### ISSUE TITLE
Return new description

### ISSUE THREAD

**Issue by dbrgn** [DanielKeep/rust-error-type#1]
This works:

``` rust
#[macro_use] extern crate error_type;

error_type! {
    #[derive(Debug)]
    pub enum MyError {
        StringError(String) {
            desc (msg) msg;
        }
    }
}

fn main() {
    println!("Hello, world!");
}
```

But if I want to prepend something to the message, I have to allocate a new string:

``` rust
error_type! {
    #[derive(Debug)]
    pub enum MyError {
        StringError(String) {
            desc (msg) format!("A StringError with the content '{}'", msg);
        }
    }
}
```

This fails of course, because the description should return a slice and I'm returning a string. Converting it to a slice does not work either:

``` rust
desc (msg) &format!("A StringError with the content '{}'", msg);
```

...because:

```
src/main.rs:7:25: 7:76 error: borrowed value does not live long enough
src/main.rs:7             desc (msg) &format!("A StringError with the content '{}'", msg);
```

Is there a way to allocate a new string, and return a slice to it with the correct lifetime?

**Comment by DanielKeep** [comment]
No; this is a fundamental limitation of `Error::description`.  You can only return a string slice which is _either_ a static string _or_ already stored in the error itself.  You _cannot_ generate a new string.  That's what `Display`/`disp` is for.

The [`Kaboom` case in the example from the docs](https://github.com/DanielKeep/rust-error-type/blob/master/src/lib.rs#L21) shows a trivial example of adding a `Display` implementation.
